name: Update LaTeX Document

on:
    workflow_dispatch:
    schedule:
      - cron: '*/1 * * * *'

permissions:
  contents: write

jobs:
    update_latex:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'

            - name: Install dependencies
              run: |
                  pip install gspread google-auth oauth2client

            - name: Fetch Google Sheets data and update LaTeX
              run: |
                  python fetch_gsheets.py
              env:
                  GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

            - name: Install LaTeX (texlive + latexmk)
              run: |
                  sudo apt-get update
                  sudo apt-get install -y texlive-latex-extra latexmk

            - name: Compile LaTeX with latexmk
              run: |
                  latexmk -pdf main.tex

            - name: Commit and push changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "Auto-update LaTeX with new entry from Google Sheets" || echo "No changes to commit"
                  git push

